services:
  backend:
    build: .
    container_name: arriendos-backend
    ports:
      - "3550:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: visionbot_bd_arriendos
    environment:
      - POSTGRES_USER=andres
      - POSTGRES_PASSWORD=andres527
      - POSTGRES_DB=arriendos_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
